#live server configurations
#######################################
#     RTMP configurations(cluster)    #
#######################################
[rtmp]
enabled = true
port = 1935

#######################################
#  push streams to other server node  #
#######################################
[[rtmp.push]]
enabled = true
address = "xiu-server-2"
port = 1935
[[rtmp.push]]
enabled = true
address = "xiu-server-3"
port = 1935


######################################
#    HLS configurations              #
######################################
[hls]
enabled = true
port = 8080


########################################
# HTTPFLV configurations               #
########################################
[httpflv]
enabled = true
port = 8081


#######################################
#   LOG configurations                #
#######################################
[log]
level = "info"
